/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/events/event-details/create-session.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/view_container';
import * as import9 from '@angular/core/src/change_detection/change_detection_util';
import * as import10 from '../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import11 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import13 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import15 from '../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import16 from '../../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import17 from '../../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import19 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/common/src/directives/ng_if';
import * as import23 from '@angular/forms/src/directives/default_value_accessor';
import * as import24 from '@angular/forms/src/directives/control_value_accessor';
import * as import25 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import26 from '@angular/forms/src/directives/ng_control';
import * as import27 from '@angular/forms/src/directives/ng_control_status';
import * as import28 from '@angular/common/src/directives/ng_class';
import * as import29 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import30 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import31 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import32 from '@angular/forms/src/directives/control_container';
export class Wrapper_CreateSessionComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CreateSessionComponent;
  /*private*/ _changed:boolean;
  subscription0:any;
  subscription1:any;
  constructor() {
    this._changed = false;
    this.context = new import0.CreateSessionComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.saveNewSession.subscribe(_eventHandler.bind(view,'saveNewSession'))); }
    if (emit1) { (this.subscription1 = this.context.cancelAddSession.subscribe(_eventHandler.bind(view,'cancelAddSession'))); }
  }
}
var renderType_CreateSessionComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_CreateSessionComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.CreateSessionComponent>;
  _CreateSessionComponent_0_3:Wrapper_CreateSessionComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CreateSessionComponent_Host0,renderType_CreateSessionComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'create-session',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CreateSessionComponent0(this.viewUtils,this,0,this._el_0);
    this._CreateSessionComponent_0_3 = new Wrapper_CreateSessionComponent();
    this.compView_0.create(this._CreateSessionComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._CreateSessionComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CreateSessionComponent) && (0 === requestNodeIndex))) { return this._CreateSessionComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CreateSessionComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CreateSessionComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CreateSessionComponentNgFactory:import7.ComponentFactory<import0.CreateSessionComponent> = new import7.ComponentFactory<import0.CreateSessionComponent>('create-session',View_CreateSessionComponent_Host0,import0.CreateSessionComponent);
const styles_CreateSessionComponent:any[] = ['em[_ngcontent-%COMP%] {float:right; color:#E05C65; padding-left:10px;}\n    .error[_ngcontent-%COMP%]   input[_ngcontent-%COMP%], .error[_ngcontent-%COMP%]   select[_ngcontent-%COMP%], .error[_ngcontent-%COMP%]   textarea[_ngcontent-%COMP%] {background-color:#E3C3C5;}\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]::-webkit-input-placeholder {color:#999;}\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]:-moz-placeholder {color:#999;}\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]::-moz-placeholder {color:#999;}\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]:-ms-input-placeholder {color:#999;}'];
class View_CreateSessionComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_CreateSessionComponent1,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_CreateSessionComponent2,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_CreateSessionComponent3,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_CreateSessionComponent4,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_CreateSessionComponent5,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_CreateSessionComponent6,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Cannot exceed 400 characters',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_CreateSessionComponent7,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'\n        Restricted words found: ',this.parentView.context.abstract.errors.restrictedWords,'        \n      ');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_CreateSessionComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_CreateSessionComponent,{});
export class View_CreateSessionComponent0 extends import1.AppView<import0.CreateSessionComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _FormGroupDirective_8_3:import10.Wrapper_FormGroupDirective;
  _ControlContainer_8_4:any;
  _NgControlStatusGroup_8_5:import11.Wrapper_NgControlStatusGroup;
  _text_9:any;
  _el_10:any;
  _NgClass_10_3:import12.Wrapper_NgClass;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import8.ViewContainer;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import13.Wrapper_NgIf;
  _text_16:any;
  _el_17:any;
  _DefaultValueAccessor_17_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_17_4:any[];
  _FormControlName_17_5:import15.Wrapper_FormControlName;
  _NgControl_17_6:any;
  _NgControlStatus_17_7:import11.Wrapper_NgControlStatus;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _NgClass_20_3:import12.Wrapper_NgClass;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _vc_25:import8.ViewContainer;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import13.Wrapper_NgIf;
  _text_26:any;
  _el_27:any;
  _DefaultValueAccessor_27_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_27_4:any[];
  _FormControlName_27_5:import15.Wrapper_FormControlName;
  _NgControl_27_6:any;
  _NgControlStatus_27_7:import11.Wrapper_NgControlStatus;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _NgClass_30_3:import12.Wrapper_NgClass;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _vc_35:import8.ViewContainer;
  _TemplateRef_35_5:any;
  _NgIf_35_6:import13.Wrapper_NgIf;
  _text_36:any;
  _el_37:any;
  _SelectControlValueAccessor_37_3:import16.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_37_4:any[];
  _FormControlName_37_5:import15.Wrapper_FormControlName;
  _NgControl_37_6:any;
  _NgControlStatus_37_7:import11.Wrapper_NgControlStatus;
  _text_38:any;
  _el_39:any;
  _NgSelectOption_39_3:import16.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_39_4:import17.Wrapper_NgSelectMultipleOption;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _NgSelectOption_42_3:import16.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_42_4:import17.Wrapper_NgSelectMultipleOption;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _NgSelectOption_45_3:import16.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_45_4:import17.Wrapper_NgSelectMultipleOption;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _NgSelectOption_48_3:import16.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_48_4:import17.Wrapper_NgSelectMultipleOption;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _NgSelectOption_51_3:import16.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_51_4:import17.Wrapper_NgSelectMultipleOption;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _NgClass_56_3:import12.Wrapper_NgClass;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _anchor_61:any;
  /*private*/ _vc_61:import8.ViewContainer;
  _TemplateRef_61_5:any;
  _NgIf_61_6:import13.Wrapper_NgIf;
  _text_62:any;
  _el_63:any;
  _SelectControlValueAccessor_63_3:import16.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_63_4:any[];
  _FormControlName_63_5:import15.Wrapper_FormControlName;
  _NgControl_63_6:any;
  _NgControlStatus_63_7:import11.Wrapper_NgControlStatus;
  _text_64:any;
  _el_65:any;
  _NgSelectOption_65_3:import16.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_65_4:import17.Wrapper_NgSelectMultipleOption;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _NgSelectOption_68_3:import16.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_68_4:import17.Wrapper_NgSelectMultipleOption;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _NgSelectOption_71_3:import16.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_71_4:import17.Wrapper_NgSelectMultipleOption;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _NgSelectOption_74_3:import16.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_74_4:import17.Wrapper_NgSelectMultipleOption;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _NgClass_79_3:import12.Wrapper_NgClass;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _anchor_84:any;
  /*private*/ _vc_84:import8.ViewContainer;
  _TemplateRef_84_5:any;
  _NgIf_84_6:import13.Wrapper_NgIf;
  _text_85:any;
  _anchor_86:any;
  /*private*/ _vc_86:import8.ViewContainer;
  _TemplateRef_86_5:any;
  _NgIf_86_6:import13.Wrapper_NgIf;
  _text_87:any;
  _anchor_88:any;
  /*private*/ _vc_88:import8.ViewContainer;
  _TemplateRef_88_5:any;
  _NgIf_88_6:import13.Wrapper_NgIf;
  _text_89:any;
  _el_90:any;
  _DefaultValueAccessor_90_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_90_4:any[];
  _FormControlName_90_5:import15.Wrapper_FormControlName;
  _NgControl_90_6:any;
  _NgControlStatus_90_7:import11.Wrapper_NgControlStatus;
  _text_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _text_98:any;
  _text_99:any;
  _map_172:any;
  _map_173:any;
  _map_174:any;
  _map_175:any;
  _map_176:any;
  /*private*/ _expr_177:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CreateSessionComponent0,renderType_CreateSessionComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._map_172 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_173 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_174 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_175 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_176 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._expr_177 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Create Session',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'form',new import3.InlineArray2(2,'autocomplete','off'),(null as any));
    this._FormGroupDirective_8_3 = new import10.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_8_4 = this._FormGroupDirective_8_3.context;
    this._NgControlStatusGroup_8_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_8_4);
    this._text_9 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_10_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import19.KeyValueDiffers,this.parentIndex),new import20.ElementRef(this._el_10),this.renderer);
    this._text_11 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'label',new import3.InlineArray2(2,'for','sessionName'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Session Name:',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_15 = new import8.ViewContainer(15,10,this,this._anchor_15);
    this._TemplateRef_15_5 = new import21.TemplateRef_(this,15,this._anchor_15);
    this._NgIf_15_6 = new import13.Wrapper_NgIf(this._vc_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_10,'input',new import3.InlineArray16(10,'class','form-control','formControlName','name','id','sessionName','placeholder','session name...','type','text'),(null as any));
    this._DefaultValueAccessor_17_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_17));
    this._NG_VALUE_ACCESSOR_17_4 = [this._DefaultValueAccessor_17_3.context];
    this._FormControlName_17_5 = new import15.Wrapper_FormControlName(this._ControlContainer_8_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_17_4);
    this._NgControl_17_6 = this._FormControlName_17_5.context;
    this._NgControlStatus_17_7 = new import11.Wrapper_NgControlStatus(this._NgControl_17_6);
    this._text_18 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_20_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import19.KeyValueDiffers,this.parentIndex),new import20.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText(this._el_20,'\n      ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'label',new import3.InlineArray2(2,'for','eventDate'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Presenter:',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n      ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._vc_25 = new import8.ViewContainer(25,20,this,this._anchor_25);
    this._TemplateRef_25_5 = new import21.TemplateRef_(this,25,this._anchor_25);
    this._NgIf_25_6 = new import13.Wrapper_NgIf(this._vc_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_20,'\n      ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_20,'input',new import3.InlineArray16(10,'class','form-control','formControlName','presenter','id','presenter','placeholder','presenter...','type','text'),(null as any));
    this._DefaultValueAccessor_27_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_27));
    this._NG_VALUE_ACCESSOR_27_4 = [this._DefaultValueAccessor_27_3.context];
    this._FormControlName_27_5 = new import15.Wrapper_FormControlName(this._ControlContainer_8_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_27_4);
    this._NgControl_27_6 = this._FormControlName_27_5.context;
    this._NgControlStatus_27_7 = new import11.Wrapper_NgControlStatus(this._NgControl_27_6);
    this._text_28 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_30_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import19.KeyValueDiffers,this.parentIndex),new import20.ElementRef(this._el_30),this.renderer);
    this._text_31 = this.renderer.createText(this._el_30,'\n      ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'label',new import3.InlineArray2(2,'for','duration'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Duration:',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n      ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_30,(null as any));
    this._vc_35 = new import8.ViewContainer(35,30,this,this._anchor_35);
    this._TemplateRef_35_5 = new import21.TemplateRef_(this,35,this._anchor_35);
    this._NgIf_35_6 = new import13.Wrapper_NgIf(this._vc_35.vcRef,this._TemplateRef_35_5);
    this._text_36 = this.renderer.createText(this._el_30,'\n      ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_30,'select',new import3.InlineArray4(4,'class','form-control','formControlName','duration'),(null as any));
    this._SelectControlValueAccessor_37_3 = new import16.Wrapper_SelectControlValueAccessor(this.renderer,new import20.ElementRef(this._el_37));
    this._NG_VALUE_ACCESSOR_37_4 = [this._SelectControlValueAccessor_37_3.context];
    this._FormControlName_37_5 = new import15.Wrapper_FormControlName(this._ControlContainer_8_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_37_4);
    this._NgControl_37_6 = this._FormControlName_37_5.context;
    this._NgControlStatus_37_7 = new import11.Wrapper_NgControlStatus(this._NgControl_37_6);
    this._text_38 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'option',new import3.InlineArray2(2,'value',''),(null as any));
    this._NgSelectOption_39_3 = new import16.Wrapper_NgSelectOption(new import20.ElementRef(this._el_39),this.renderer,this._SelectControlValueAccessor_37_3.context);
    this._NgSelectMultipleOption_39_4 = new import17.Wrapper_NgSelectMultipleOption(new import20.ElementRef(this._el_39),this.renderer,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'select duration...',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_37,'option',new import3.InlineArray2(2,'value','1'),(null as any));
    this._NgSelectOption_42_3 = new import16.Wrapper_NgSelectOption(new import20.ElementRef(this._el_42),this.renderer,this._SelectControlValueAccessor_37_3.context);
    this._NgSelectMultipleOption_42_4 = new import17.Wrapper_NgSelectMultipleOption(new import20.ElementRef(this._el_42),this.renderer,(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Half Hour',(null as any));
    this._text_44 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_37,'option',new import3.InlineArray2(2,'value','2'),(null as any));
    this._NgSelectOption_45_3 = new import16.Wrapper_NgSelectOption(new import20.ElementRef(this._el_45),this.renderer,this._SelectControlValueAccessor_37_3.context);
    this._NgSelectMultipleOption_45_4 = new import17.Wrapper_NgSelectMultipleOption(new import20.ElementRef(this._el_45),this.renderer,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'1 Hour',(null as any));
    this._text_47 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_37,'option',new import3.InlineArray2(2,'value','3'),(null as any));
    this._NgSelectOption_48_3 = new import16.Wrapper_NgSelectOption(new import20.ElementRef(this._el_48),this.renderer,this._SelectControlValueAccessor_37_3.context);
    this._NgSelectMultipleOption_48_4 = new import17.Wrapper_NgSelectMultipleOption(new import20.ElementRef(this._el_48),this.renderer,(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Half Day',(null as any));
    this._text_50 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_37,'option',new import3.InlineArray2(2,'value','4'),(null as any));
    this._NgSelectOption_51_3 = new import16.Wrapper_NgSelectOption(new import20.ElementRef(this._el_51),this.renderer,this._SelectControlValueAccessor_37_3.context);
    this._NgSelectMultipleOption_51_4 = new import17.Wrapper_NgSelectMultipleOption(new import20.ElementRef(this._el_51),this.renderer,(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'Full Day',(null as any));
    this._text_53 = this.renderer.createText(this._el_37,'\n      ',(null as any));
    this._text_54 = this.renderer.createText(this._el_30,'\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_56_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import19.KeyValueDiffers,this.parentIndex),new import20.ElementRef(this._el_56),this.renderer);
    this._text_57 = this.renderer.createText(this._el_56,'\n      ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_56,'label',new import3.InlineArray2(2,'for','level'),(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'Level:',(null as any));
    this._text_60 = this.renderer.createText(this._el_56,'\n      ',(null as any));
    this._anchor_61 = this.renderer.createTemplateAnchor(this._el_56,(null as any));
    this._vc_61 = new import8.ViewContainer(61,56,this,this._anchor_61);
    this._TemplateRef_61_5 = new import21.TemplateRef_(this,61,this._anchor_61);
    this._NgIf_61_6 = new import13.Wrapper_NgIf(this._vc_61.vcRef,this._TemplateRef_61_5);
    this._text_62 = this.renderer.createText(this._el_56,'\n      ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_56,'select',new import3.InlineArray8(6,'class','form-control','formControlName','level','ngControl','level'),(null as any));
    this._SelectControlValueAccessor_63_3 = new import16.Wrapper_SelectControlValueAccessor(this.renderer,new import20.ElementRef(this._el_63));
    this._NG_VALUE_ACCESSOR_63_4 = [this._SelectControlValueAccessor_63_3.context];
    this._FormControlName_63_5 = new import15.Wrapper_FormControlName(this._ControlContainer_8_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_63_4);
    this._NgControl_63_6 = this._FormControlName_63_5.context;
    this._NgControlStatus_63_7 = new import11.Wrapper_NgControlStatus(this._NgControl_63_6);
    this._text_64 = this.renderer.createText(this._el_63,'\n        ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_63,'option',new import3.InlineArray2(2,'value',''),(null as any));
    this._NgSelectOption_65_3 = new import16.Wrapper_NgSelectOption(new import20.ElementRef(this._el_65),this.renderer,this._SelectControlValueAccessor_63_3.context);
    this._NgSelectMultipleOption_65_4 = new import17.Wrapper_NgSelectMultipleOption(new import20.ElementRef(this._el_65),this.renderer,(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'select level...',(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n        ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_63,'option',new import3.InlineArray2(2,'value','Beginner'),(null as any));
    this._NgSelectOption_68_3 = new import16.Wrapper_NgSelectOption(new import20.ElementRef(this._el_68),this.renderer,this._SelectControlValueAccessor_63_3.context);
    this._NgSelectMultipleOption_68_4 = new import17.Wrapper_NgSelectMultipleOption(new import20.ElementRef(this._el_68),this.renderer,(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Beginner',(null as any));
    this._text_70 = this.renderer.createText(this._el_63,'\n        ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_63,'option',new import3.InlineArray2(2,'value','Intermediate'),(null as any));
    this._NgSelectOption_71_3 = new import16.Wrapper_NgSelectOption(new import20.ElementRef(this._el_71),this.renderer,this._SelectControlValueAccessor_63_3.context);
    this._NgSelectMultipleOption_71_4 = new import17.Wrapper_NgSelectMultipleOption(new import20.ElementRef(this._el_71),this.renderer,(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'Intermediate',(null as any));
    this._text_73 = this.renderer.createText(this._el_63,'\n        ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_63,'option',new import3.InlineArray2(2,'value','Advanced'),(null as any));
    this._NgSelectOption_74_3 = new import16.Wrapper_NgSelectOption(new import20.ElementRef(this._el_74),this.renderer,this._SelectControlValueAccessor_63_3.context);
    this._NgSelectMultipleOption_74_4 = new import17.Wrapper_NgSelectMultipleOption(new import20.ElementRef(this._el_74),this.renderer,(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'Advanced',(null as any));
    this._text_76 = this.renderer.createText(this._el_63,'\n      ',(null as any));
    this._text_77 = this.renderer.createText(this._el_56,'\n    ',(null as any));
    this._text_78 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_79_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import19.KeyValueDiffers,this.parentIndex),new import20.ElementRef(this._el_79),this.renderer);
    this._text_80 = this.renderer.createText(this._el_79,'\n      ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_79,'label',new import3.InlineArray2(2,'for','abstract'),(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'Abstract:',(null as any));
    this._text_83 = this.renderer.createText(this._el_79,'\n      ',(null as any));
    this._anchor_84 = this.renderer.createTemplateAnchor(this._el_79,(null as any));
    this._vc_84 = new import8.ViewContainer(84,79,this,this._anchor_84);
    this._TemplateRef_84_5 = new import21.TemplateRef_(this,84,this._anchor_84);
    this._NgIf_84_6 = new import13.Wrapper_NgIf(this._vc_84.vcRef,this._TemplateRef_84_5);
    this._text_85 = this.renderer.createText(this._el_79,'\n      ',(null as any));
    this._anchor_86 = this.renderer.createTemplateAnchor(this._el_79,(null as any));
    this._vc_86 = new import8.ViewContainer(86,79,this,this._anchor_86);
    this._TemplateRef_86_5 = new import21.TemplateRef_(this,86,this._anchor_86);
    this._NgIf_86_6 = new import13.Wrapper_NgIf(this._vc_86.vcRef,this._TemplateRef_86_5);
    this._text_87 = this.renderer.createText(this._el_79,'\n      ',(null as any));
    this._anchor_88 = this.renderer.createTemplateAnchor(this._el_79,(null as any));
    this._vc_88 = new import8.ViewContainer(88,79,this,this._anchor_88);
    this._TemplateRef_88_5 = new import21.TemplateRef_(this,88,this._anchor_88);
    this._NgIf_88_6 = new import13.Wrapper_NgIf(this._vc_88.vcRef,this._TemplateRef_88_5);
    this._text_89 = this.renderer.createText(this._el_79,'\n      ',(null as any));
    this._el_90 = import3.createRenderElement(this.renderer,this._el_79,'textarea',new import3.InlineArray16(10,'class','form-control','formControlName','abstract','id','abstract','placeholder','abstract...','rows','3'),(null as any));
    this._DefaultValueAccessor_90_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_90));
    this._NG_VALUE_ACCESSOR_90_4 = [this._DefaultValueAccessor_90_3.context];
    this._FormControlName_90_5 = new import15.Wrapper_FormControlName(this._ControlContainer_8_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_90_4);
    this._NgControl_90_6 = this._FormControlName_90_5.context;
    this._NgControlStatus_90_7 = new import11.Wrapper_NgControlStatus(this._NgControl_90_6);
    this._text_91 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._text_92 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_93 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_94 = this.renderer.createText(this._el_93,'Save',(null as any));
    this._text_95 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_96 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray4(4,'class','btn btn-default','type','button'),(null as any));
    this._text_97 = this.renderer.createText(this._el_96,'Cancel',(null as any));
    this._text_98 = this.renderer.createText(this._el_8,'\n  ',(null as any));
    this._text_99 = this.renderer.createText(this._el_6,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_8));
    this._FormGroupDirective_8_3.subscribe(this,this.eventHandler(this.handleEvent_8),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_17));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_27,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_27));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_37,new import3.InlineArray4(4,'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_37));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_63,new import3.InlineArray4(4,'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_63));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_90,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_90));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_96,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_96));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._anchor_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._anchor_84,
      this._text_85,
      this._anchor_86,
      this._text_87,
      this._anchor_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._text_98,
      this._text_99
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import22.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6.context; }
    if (((token === import23.DefaultValueAccessor) && (17 === requestNodeIndex))) { return this._DefaultValueAccessor_17_3.context; }
    if (((token === import24.NG_VALUE_ACCESSOR) && (17 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_17_4; }
    if (((token === import25.FormControlName) && (17 === requestNodeIndex))) { return this._FormControlName_17_5.context; }
    if (((token === import26.NgControl) && (17 === requestNodeIndex))) { return this._NgControl_17_6; }
    if (((token === import27.NgControlStatus) && (17 === requestNodeIndex))) { return this._NgControlStatus_17_7.context; }
    if (((token === import28.NgClass) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NgClass_10_3.context; }
    if (((token === import21.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import22.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6.context; }
    if (((token === import23.DefaultValueAccessor) && (27 === requestNodeIndex))) { return this._DefaultValueAccessor_27_3.context; }
    if (((token === import24.NG_VALUE_ACCESSOR) && (27 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_27_4; }
    if (((token === import25.FormControlName) && (27 === requestNodeIndex))) { return this._FormControlName_27_5.context; }
    if (((token === import26.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_6; }
    if (((token === import27.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_7.context; }
    if (((token === import28.NgClass) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._NgClass_20_3.context; }
    if (((token === import21.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import22.NgIf) && (35 === requestNodeIndex))) { return this._NgIf_35_6.context; }
    if (((token === import29.NgSelectOption) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NgSelectOption_39_3.context; }
    if (((token === import30.NgSelectMultipleOption) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NgSelectMultipleOption_39_4.context; }
    if (((token === import29.NgSelectOption) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgSelectOption_42_3.context; }
    if (((token === import30.NgSelectMultipleOption) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgSelectMultipleOption_42_4.context; }
    if (((token === import29.NgSelectOption) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgSelectOption_45_3.context; }
    if (((token === import30.NgSelectMultipleOption) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgSelectMultipleOption_45_4.context; }
    if (((token === import29.NgSelectOption) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._NgSelectOption_48_3.context; }
    if (((token === import30.NgSelectMultipleOption) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._NgSelectMultipleOption_48_4.context; }
    if (((token === import29.NgSelectOption) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NgSelectOption_51_3.context; }
    if (((token === import30.NgSelectMultipleOption) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NgSelectMultipleOption_51_4.context; }
    if (((token === import29.SelectControlValueAccessor) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._SelectControlValueAccessor_37_3.context; }
    if (((token === import24.NG_VALUE_ACCESSOR) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NG_VALUE_ACCESSOR_37_4; }
    if (((token === import25.FormControlName) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._FormControlName_37_5.context; }
    if (((token === import26.NgControl) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NgControl_37_6; }
    if (((token === import27.NgControlStatus) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NgControlStatus_37_7.context; }
    if (((token === import28.NgClass) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._NgClass_30_3.context; }
    if (((token === import21.TemplateRef) && (61 === requestNodeIndex))) { return this._TemplateRef_61_5; }
    if (((token === import22.NgIf) && (61 === requestNodeIndex))) { return this._NgIf_61_6.context; }
    if (((token === import29.NgSelectOption) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._NgSelectOption_65_3.context; }
    if (((token === import30.NgSelectMultipleOption) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._NgSelectMultipleOption_65_4.context; }
    if (((token === import29.NgSelectOption) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgSelectOption_68_3.context; }
    if (((token === import30.NgSelectMultipleOption) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgSelectMultipleOption_68_4.context; }
    if (((token === import29.NgSelectOption) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._NgSelectOption_71_3.context; }
    if (((token === import30.NgSelectMultipleOption) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._NgSelectMultipleOption_71_4.context; }
    if (((token === import29.NgSelectOption) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._NgSelectOption_74_3.context; }
    if (((token === import30.NgSelectMultipleOption) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._NgSelectMultipleOption_74_4.context; }
    if (((token === import29.SelectControlValueAccessor) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._SelectControlValueAccessor_63_3.context; }
    if (((token === import24.NG_VALUE_ACCESSOR) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._NG_VALUE_ACCESSOR_63_4; }
    if (((token === import25.FormControlName) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._FormControlName_63_5.context; }
    if (((token === import26.NgControl) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._NgControl_63_6; }
    if (((token === import27.NgControlStatus) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._NgControlStatus_63_7.context; }
    if (((token === import28.NgClass) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 77)))) { return this._NgClass_56_3.context; }
    if (((token === import21.TemplateRef) && (84 === requestNodeIndex))) { return this._TemplateRef_84_5; }
    if (((token === import22.NgIf) && (84 === requestNodeIndex))) { return this._NgIf_84_6.context; }
    if (((token === import21.TemplateRef) && (86 === requestNodeIndex))) { return this._TemplateRef_86_5; }
    if (((token === import22.NgIf) && (86 === requestNodeIndex))) { return this._NgIf_86_6.context; }
    if (((token === import21.TemplateRef) && (88 === requestNodeIndex))) { return this._TemplateRef_88_5; }
    if (((token === import22.NgIf) && (88 === requestNodeIndex))) { return this._NgIf_88_6.context; }
    if (((token === import23.DefaultValueAccessor) && (90 === requestNodeIndex))) { return this._DefaultValueAccessor_90_3.context; }
    if (((token === import24.NG_VALUE_ACCESSOR) && (90 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_90_4; }
    if (((token === import25.FormControlName) && (90 === requestNodeIndex))) { return this._FormControlName_90_5.context; }
    if (((token === import26.NgControl) && (90 === requestNodeIndex))) { return this._NgControl_90_6; }
    if (((token === import27.NgControlStatus) && (90 === requestNodeIndex))) { return this._NgControlStatus_90_7.context; }
    if (((token === import28.NgClass) && ((79 <= requestNodeIndex) && (requestNodeIndex <= 91)))) { return this._NgClass_79_3.context; }
    if (((token === import31.FormGroupDirective) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 98)))) { return this._FormGroupDirective_8_3.context; }
    if (((token === import32.ControlContainer) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 98)))) { return this._ControlContainer_8_4; }
    if (((token === import27.NgControlStatusGroup) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 98)))) { return this._NgControlStatusGroup_8_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8_0_0:any = this.context.newSessionForm;
    this._FormGroupDirective_8_3.check_form(currVal_8_0_0,throwOnChange,false);
    this._FormGroupDirective_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    this._NgControlStatusGroup_8_5.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_10_0_0:any = 'form-group';
    this._NgClass_10_3.check_klass(currVal_10_0_0,throwOnChange,false);
    const currVal_10_0_1:any = this._map_172((this.context.name.invalid && this.context.name.dirty));
    this._NgClass_10_3.check_ngClass(currVal_10_0_1,throwOnChange,false);
    this._NgClass_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_15_0_0:any = (this.context.name.invalid && this.context.name.dirty);
    this._NgIf_15_6.check_ngIf(currVal_15_0_0,throwOnChange,false);
    this._NgIf_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    this._DefaultValueAccessor_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_17_1_0:any = 'name';
    this._FormControlName_17_5.check_name(currVal_17_1_0,throwOnChange,false);
    this._FormControlName_17_5.ngDoCheck(this,this._el_17,throwOnChange);
    this._NgControlStatus_17_7.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_20_0_0:any = 'form-group';
    this._NgClass_20_3.check_klass(currVal_20_0_0,throwOnChange,false);
    const currVal_20_0_1:any = this._map_173((this.context.presenter.invalid && this.context.presenter.dirty));
    this._NgClass_20_3.check_ngClass(currVal_20_0_1,throwOnChange,false);
    this._NgClass_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_25_0_0:any = (this.context.presenter.invalid && this.context.presenter.dirty);
    this._NgIf_25_6.check_ngIf(currVal_25_0_0,throwOnChange,false);
    this._NgIf_25_6.ngDoCheck(this,this._anchor_25,throwOnChange);
    this._DefaultValueAccessor_27_3.ngDoCheck(this,this._el_27,throwOnChange);
    const currVal_27_1_0:any = 'presenter';
    this._FormControlName_27_5.check_name(currVal_27_1_0,throwOnChange,false);
    this._FormControlName_27_5.ngDoCheck(this,this._el_27,throwOnChange);
    this._NgControlStatus_27_7.ngDoCheck(this,this._el_27,throwOnChange);
    const currVal_30_0_0:any = 'form-group';
    this._NgClass_30_3.check_klass(currVal_30_0_0,throwOnChange,false);
    const currVal_30_0_1:any = this._map_174((this.context.duration.invalid && this.context.duration.dirty));
    this._NgClass_30_3.check_ngClass(currVal_30_0_1,throwOnChange,false);
    this._NgClass_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    const currVal_35_0_0:any = (this.context.duration.invalid && this.context.duration.dirty);
    this._NgIf_35_6.check_ngIf(currVal_35_0_0,throwOnChange,false);
    this._NgIf_35_6.ngDoCheck(this,this._anchor_35,throwOnChange);
    this._SelectControlValueAccessor_37_3.ngDoCheck(this,this._el_37,throwOnChange);
    const currVal_37_1_0:any = 'duration';
    this._FormControlName_37_5.check_name(currVal_37_1_0,throwOnChange,false);
    this._FormControlName_37_5.ngDoCheck(this,this._el_37,throwOnChange);
    this._NgControlStatus_37_7.ngDoCheck(this,this._el_37,throwOnChange);
    const currVal_39_0_0:any = '';
    this._NgSelectOption_39_3.check_value(currVal_39_0_0,throwOnChange,false);
    this._NgSelectOption_39_3.ngDoCheck(this,this._el_39,throwOnChange);
    const currVal_39_1_0:any = '';
    this._NgSelectMultipleOption_39_4.check_value(currVal_39_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_39_4.ngDoCheck(this,this._el_39,throwOnChange);
    const currVal_42_0_0:any = '1';
    this._NgSelectOption_42_3.check_value(currVal_42_0_0,throwOnChange,false);
    this._NgSelectOption_42_3.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_42_1_0:any = '1';
    this._NgSelectMultipleOption_42_4.check_value(currVal_42_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_42_4.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_45_0_0:any = '2';
    this._NgSelectOption_45_3.check_value(currVal_45_0_0,throwOnChange,false);
    this._NgSelectOption_45_3.ngDoCheck(this,this._el_45,throwOnChange);
    const currVal_45_1_0:any = '2';
    this._NgSelectMultipleOption_45_4.check_value(currVal_45_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_45_4.ngDoCheck(this,this._el_45,throwOnChange);
    const currVal_48_0_0:any = '3';
    this._NgSelectOption_48_3.check_value(currVal_48_0_0,throwOnChange,false);
    this._NgSelectOption_48_3.ngDoCheck(this,this._el_48,throwOnChange);
    const currVal_48_1_0:any = '3';
    this._NgSelectMultipleOption_48_4.check_value(currVal_48_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_48_4.ngDoCheck(this,this._el_48,throwOnChange);
    const currVal_51_0_0:any = '4';
    this._NgSelectOption_51_3.check_value(currVal_51_0_0,throwOnChange,false);
    this._NgSelectOption_51_3.ngDoCheck(this,this._el_51,throwOnChange);
    const currVal_51_1_0:any = '4';
    this._NgSelectMultipleOption_51_4.check_value(currVal_51_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_51_4.ngDoCheck(this,this._el_51,throwOnChange);
    const currVal_56_0_0:any = 'form-group';
    this._NgClass_56_3.check_klass(currVal_56_0_0,throwOnChange,false);
    const currVal_56_0_1:any = this._map_175((this.context.level.invalid && this.context.level.dirty));
    this._NgClass_56_3.check_ngClass(currVal_56_0_1,throwOnChange,false);
    this._NgClass_56_3.ngDoCheck(this,this._el_56,throwOnChange);
    const currVal_61_0_0:any = (this.context.level.invalid && this.context.level.dirty);
    this._NgIf_61_6.check_ngIf(currVal_61_0_0,throwOnChange,false);
    this._NgIf_61_6.ngDoCheck(this,this._anchor_61,throwOnChange);
    this._SelectControlValueAccessor_63_3.ngDoCheck(this,this._el_63,throwOnChange);
    const currVal_63_1_0:any = 'level';
    this._FormControlName_63_5.check_name(currVal_63_1_0,throwOnChange,false);
    this._FormControlName_63_5.ngDoCheck(this,this._el_63,throwOnChange);
    this._NgControlStatus_63_7.ngDoCheck(this,this._el_63,throwOnChange);
    const currVal_65_0_0:any = '';
    this._NgSelectOption_65_3.check_value(currVal_65_0_0,throwOnChange,false);
    this._NgSelectOption_65_3.ngDoCheck(this,this._el_65,throwOnChange);
    const currVal_65_1_0:any = '';
    this._NgSelectMultipleOption_65_4.check_value(currVal_65_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_65_4.ngDoCheck(this,this._el_65,throwOnChange);
    const currVal_68_0_0:any = 'Beginner';
    this._NgSelectOption_68_3.check_value(currVal_68_0_0,throwOnChange,false);
    this._NgSelectOption_68_3.ngDoCheck(this,this._el_68,throwOnChange);
    const currVal_68_1_0:any = 'Beginner';
    this._NgSelectMultipleOption_68_4.check_value(currVal_68_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_68_4.ngDoCheck(this,this._el_68,throwOnChange);
    const currVal_71_0_0:any = 'Intermediate';
    this._NgSelectOption_71_3.check_value(currVal_71_0_0,throwOnChange,false);
    this._NgSelectOption_71_3.ngDoCheck(this,this._el_71,throwOnChange);
    const currVal_71_1_0:any = 'Intermediate';
    this._NgSelectMultipleOption_71_4.check_value(currVal_71_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_71_4.ngDoCheck(this,this._el_71,throwOnChange);
    const currVal_74_0_0:any = 'Advanced';
    this._NgSelectOption_74_3.check_value(currVal_74_0_0,throwOnChange,false);
    this._NgSelectOption_74_3.ngDoCheck(this,this._el_74,throwOnChange);
    const currVal_74_1_0:any = 'Advanced';
    this._NgSelectMultipleOption_74_4.check_value(currVal_74_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_74_4.ngDoCheck(this,this._el_74,throwOnChange);
    const currVal_79_0_0:any = 'form-group';
    this._NgClass_79_3.check_klass(currVal_79_0_0,throwOnChange,false);
    const currVal_79_0_1:any = this._map_176((this.context.abstract.invalid && this.context.abstract.dirty));
    this._NgClass_79_3.check_ngClass(currVal_79_0_1,throwOnChange,false);
    this._NgClass_79_3.ngDoCheck(this,this._el_79,throwOnChange);
    const currVal_84_0_0:any = ((this.context.abstract.invalid && this.context.abstract.dirty) && this.context.abstract.errors.required);
    this._NgIf_84_6.check_ngIf(currVal_84_0_0,throwOnChange,false);
    this._NgIf_84_6.ngDoCheck(this,this._anchor_84,throwOnChange);
    const currVal_86_0_0:any = ((this.context.abstract.invalid && this.context.abstract.dirty) && this.context.abstract.errors.maxLength);
    this._NgIf_86_6.check_ngIf(currVal_86_0_0,throwOnChange,false);
    this._NgIf_86_6.ngDoCheck(this,this._anchor_86,throwOnChange);
    const currVal_88_0_0:any = ((this.context.abstract.invalid && this.context.abstract.dirty) && this.context.abstract.errors.restrictedWords);
    this._NgIf_88_6.check_ngIf(currVal_88_0_0,throwOnChange,false);
    this._NgIf_88_6.ngDoCheck(this,this._anchor_88,throwOnChange);
    this._DefaultValueAccessor_90_3.ngDoCheck(this,this._el_90,throwOnChange);
    const currVal_90_1_0:any = 'abstract';
    this._FormControlName_90_5.check_name(currVal_90_1_0,throwOnChange,false);
    this._FormControlName_90_5.ngDoCheck(this,this._el_90,throwOnChange);
    this._NgControlStatus_90_7.ngDoCheck(this,this._el_90,throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._vc_25.detectChangesInNestedViews(throwOnChange);
    this._vc_35.detectChangesInNestedViews(throwOnChange);
    this._vc_61.detectChangesInNestedViews(throwOnChange);
    this._vc_84.detectChangesInNestedViews(throwOnChange);
    this._vc_86.detectChangesInNestedViews(throwOnChange);
    this._vc_88.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_8_5.checkHost(this,this,this._el_8,throwOnChange);
    this._NgControlStatus_17_7.checkHost(this,this,this._el_17,throwOnChange);
    this._NgControlStatus_27_7.checkHost(this,this,this._el_27,throwOnChange);
    this._NgControlStatus_37_7.checkHost(this,this,this._el_37,throwOnChange);
    this._NgControlStatus_63_7.checkHost(this,this,this._el_63,throwOnChange);
    this._NgControlStatus_90_7.checkHost(this,this,this._el_90,throwOnChange);
    const currVal_177:any = this.context.newSessionForm.invalid;
    if (import3.checkBinding(throwOnChange,this._expr_177,currVal_177)) {
      this.renderer.setElementProperty(this._el_93,'disabled',currVal_177);
      this._expr_177 = currVal_177;
    }
  }
  destroyInternal():void {
    this._vc_15.destroyNestedViews();
    this._vc_25.destroyNestedViews();
    this._vc_35.destroyNestedViews();
    this._vc_61.destroyNestedViews();
    this._vc_84.destroyNestedViews();
    this._vc_86.destroyNestedViews();
    this._vc_88.destroyNestedViews();
    this._FormControlName_17_5.ngOnDestroy();
    this._FormControlName_27_5.ngOnDestroy();
    this._NgSelectOption_39_3.ngOnDestroy();
    this._NgSelectMultipleOption_39_4.ngOnDestroy();
    this._NgSelectOption_42_3.ngOnDestroy();
    this._NgSelectMultipleOption_42_4.ngOnDestroy();
    this._NgSelectOption_45_3.ngOnDestroy();
    this._NgSelectMultipleOption_45_4.ngOnDestroy();
    this._NgSelectOption_48_3.ngOnDestroy();
    this._NgSelectMultipleOption_48_4.ngOnDestroy();
    this._NgSelectOption_51_3.ngOnDestroy();
    this._NgSelectMultipleOption_51_4.ngOnDestroy();
    this._FormControlName_37_5.ngOnDestroy();
    this._NgSelectOption_65_3.ngOnDestroy();
    this._NgSelectMultipleOption_65_4.ngOnDestroy();
    this._NgSelectOption_68_3.ngOnDestroy();
    this._NgSelectMultipleOption_68_4.ngOnDestroy();
    this._NgSelectOption_71_3.ngOnDestroy();
    this._NgSelectMultipleOption_71_4.ngOnDestroy();
    this._NgSelectOption_74_3.ngOnDestroy();
    this._NgSelectMultipleOption_74_4.ngOnDestroy();
    this._FormControlName_63_5.ngOnDestroy();
    this._FormControlName_90_5.ngOnDestroy();
    this._FormGroupDirective_8_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 15)) { return new View_CreateSessionComponent1(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    if ((nodeIndex == 25)) { return new View_CreateSessionComponent2(this.viewUtils,this,25,this._anchor_25,this._vc_25); }
    if ((nodeIndex == 35)) { return new View_CreateSessionComponent3(this.viewUtils,this,35,this._anchor_35,this._vc_35); }
    if ((nodeIndex == 61)) { return new View_CreateSessionComponent4(this.viewUtils,this,61,this._anchor_61,this._vc_61); }
    if ((nodeIndex == 84)) { return new View_CreateSessionComponent5(this.viewUtils,this,84,this._anchor_84,this._vc_84); }
    if ((nodeIndex == 86)) { return new View_CreateSessionComponent6(this.viewUtils,this,86,this._anchor_86,this._vc_86); }
    if ((nodeIndex == 88)) { return new View_CreateSessionComponent7(this.viewUtils,this,88,this._anchor_88,this._vc_88); }
    return (null as any);
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_8_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.saveSession(this.context.newSessionForm.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_17_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_27(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_27_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_37(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_37_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_63(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_63_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_90(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_90_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_96(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.cancel()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}