/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/events/event-details/event-details.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../app/events/shared/event.service';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '@angular/core/src/change_detection/change_detection_util';
import * as import12 from '../../../../app/events/event-details/session-list.component';
import * as import13 from './session-list.component.ngfactory';
import * as import14 from '../../../../app/user/auth.service';
import * as import15 from '../../../../app/events/event-details/voter.service';
import * as import16 from '../../../../app/events/event-details/create-session.component';
import * as import17 from './create-session.component.ngfactory';
import * as import18 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import19 from '@angular/common/src/pipes/uppercase_pipe';
import * as import20 from '@angular/common/src/pipes/date_pipe';
import * as import21 from '@angular/common/src/pipes/number_pipe';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/core/src/i18n/tokens';
import * as import24 from '@angular/common/src/directives/ng_if';
import * as import25 from '@angular/core/src/security';
export class Wrapper_EventDetailsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.EventDetailsComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.EventDetailsComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_EventDetailsComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_EventDetailsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.EventDetailsComponent>;
  _EventDetailsComponent_0_3:Wrapper_EventDetailsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventDetailsComponent_Host0,renderType_EventDetailsComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_EventDetailsComponent0(this.viewUtils,this,0,this._el_0);
    this._EventDetailsComponent_0_3 = new Wrapper_EventDetailsComponent(this.injectorGet(import8.EventService,this.parentIndex),this.injectorGet(import9.ActivatedRoute,this.parentIndex));
    this.compView_0.create(this._EventDetailsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._EventDetailsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EventDetailsComponent) && (0 === requestNodeIndex))) { return this._EventDetailsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EventDetailsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const EventDetailsComponentNgFactory:import7.ComponentFactory<import0.EventDetailsComponent> = new import7.ComponentFactory<import0.EventDetailsComponent>('ng-component',View_EventDetailsComponent_Host0,import0.EventDetailsComponent);
const styles_EventDetailsComponent:any[] = ['.container[_ngcontent-%COMP%] { padding-left:20px; padding-right:20px; }\n    .event-image[_ngcontent-%COMP%] { height:100px; }\n    a[_ngcontent-%COMP%] { cursor:pointer }'];
class View_EventDetailsComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_EventDetailsComponent1,renderType_EventDetailsComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_11 = import11.UNINITIALIZED;
    this._expr_12 = import11.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'address',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Address:',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_11:any = import3.inlineInterpolate(1,'\n        ',((this.parentView.context.event == null)? (null as any): ((this.parentView.context.event.location == null)? (null as any): this.parentView.context.event.location.address)),'');
    if (import3.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_7,currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = import3.inlineInterpolate(2,'\n        ',((this.parentView.context.event == null)? (null as any): ((this.parentView.context.event.location == null)? (null as any): this.parentView.context.event.location.city)),', ',((this.parentView.context.event == null)? (null as any): ((this.parentView.context.event.location == null)? (null as any): this.parentView.context.event.location.country)),'\n      ');
    if (import3.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_9,currVal_12);
      this._expr_12 = currVal_12;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_EventDetailsComponent2 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import12.SessionListComponent>;
  _SessionListComponent_0_3:import13.Wrapper_SessionListComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_EventDetailsComponent2,renderType_EventDetailsComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'session-list',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import13.View_SessionListComponent0(this.viewUtils,this,0,this._el_0);
    this._SessionListComponent_0_3 = new import13.Wrapper_SessionListComponent(this.parentView.parentView.injectorGet(import14.AuthService,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import15.VoterService,this.parentView.parentIndex));
    this.compView_0.create(this._SessionListComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.SessionListComponent) && (0 === requestNodeIndex))) { return this._SessionListComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = ((this.parentView.context.event == null)? (null as any): this.parentView.context.event.sessions);
    this._SessionListComponent_0_3.check_sessions(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.filterBy;
    this._SessionListComponent_0_3.check_filterBy(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = this.parentView.context.sortBy;
    this._SessionListComponent_0_3.check_sortBy(currVal_0_0_2,throwOnChange,false);
    const currVal_0_0_3:any = ((this.parentView.context.event == null)? (null as any): this.parentView.context.event.id);
    this._SessionListComponent_0_3.check_eventId(currVal_0_0_3,throwOnChange,false);
    this._SessionListComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_EventDetailsComponent3 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import16.CreateSessionComponent>;
  _CreateSessionComponent_0_3:import17.Wrapper_CreateSessionComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_EventDetailsComponent3,renderType_EventDetailsComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'create-session',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import17.View_CreateSessionComponent0(this.viewUtils,this,0,this._el_0);
    this._CreateSessionComponent_0_3 = new import17.Wrapper_CreateSessionComponent();
    this.compView_0.create(this._CreateSessionComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'saveNewSession',(null as any),'cancelAddSession',(null as any)),this.eventHandler(this.handleEvent_0));
    this._CreateSessionComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.CreateSessionComponent) && (0 === requestNodeIndex))) { return this._CreateSessionComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CreateSessionComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CreateSessionComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'saveNewSession')) {
      const pd_sub_0:any = ((<any>this.parentView.context.saveNewSession($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'cancelAddSession')) {
      const pd_sub_1:any = ((<any>this.parentView.context.cancelAddSession()) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
var renderType_EventDetailsComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_EventDetailsComponent,{});
export class View_EventDetailsComponent0 extends import1.AppView<import0.EventDetailsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _vc_33:import10.ViewContainer;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import18.Wrapper_NgIf;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _anchor_80:any;
  /*private*/ _vc_80:import10.ViewContainer;
  _TemplateRef_80_5:any;
  _NgIf_80_6:import18.Wrapper_NgIf;
  _text_81:any;
  _anchor_82:any;
  /*private*/ _vc_82:import10.ViewContainer;
  _TemplateRef_82_5:any;
  _NgIf_82_6:import18.Wrapper_NgIf;
  _text_83:any;
  /*private*/ _expr_93:any;
  /*private*/ _expr_94:any;
  /*private*/ _expr_95:any;
  _pipe_uppercase_0:import19.UpperCasePipe;
  _pipe_uppercase_0_0:any;
  /*private*/ _expr_98:any;
  _pipe_date_1:import20.DatePipe;
  _pipe_date_1_0:any;
  /*private*/ _expr_101:any;
  /*private*/ _expr_102:any;
  _pipe_currency_2:import21.CurrencyPipe;
  _pipe_currency_2_0:any;
  /*private*/ _expr_105:any;
  /*private*/ _expr_106:any;
  /*private*/ _expr_107:any;
  /*private*/ _expr_108:any;
  /*private*/ _expr_109:any;
  /*private*/ _expr_110:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventDetailsComponent0,renderType_EventDetailsComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_93 = import11.UNINITIALIZED;
    this._expr_94 = import11.UNINITIALIZED;
    this._expr_95 = import11.UNINITIALIZED;
    this._expr_98 = import11.UNINITIALIZED;
    this._expr_101 = import11.UNINITIALIZED;
    this._expr_102 = import11.UNINITIALIZED;
    this._expr_105 = import11.UNINITIALIZED;
    this._expr_106 = import11.UNINITIALIZED;
    this._expr_107 = import11.UNINITIALIZED;
    this._expr_108 = import11.UNINITIALIZED;
    this._expr_109 = import11.UNINITIALIZED;
    this._expr_110 = import11.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'class','event-image'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-md-11'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Date:',(null as any));
    this._text_20 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_15,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_22,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Time:',(null as any));
    this._text_25 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_26 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_15,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_27,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Price:',(null as any));
    this._text_30 = this.renderer.createText(this._el_27,'',(null as any));
    this._text_31 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._vc_33 = new import10.ViewContainer(33,13,this,this._anchor_33);
    this._TemplateRef_33_5 = new import22.TemplateRef_(this,33,this._anchor_33);
    this._NgIf_33_6 = new import18.Wrapper_NgIf(this._vc_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_13,'\n  ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray4(4,'class','row','style','margin-bottom:10px'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n    ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'div',new import3.InlineArray2(2,'class','col-md-2'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n      ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'h3',new import3.InlineArray2(2,'style','margin:0'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Sessions',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_38,'\n    ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_38,'div',new import3.InlineArray2(2,'class','col-md-7'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'div',new import3.InlineArray4(4,'class','btn-group btn-group-sm','style','margin-right:20px; margin-left:20px;'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'By Name',(null as any));
    this._text_52 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_48,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'By Votes',(null as any));
    this._text_55 = this.renderer.createText(this._el_48,'\n      ',(null as any));
    this._text_56 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_46,'div',new import3.InlineArray2(2,'class','btn-group btn-group-sm'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_57,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'All',(null as any));
    this._text_61 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_57,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'Beginner',(null as any));
    this._text_64 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_57,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'Intermediate',(null as any));
    this._text_67 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_57,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Advanced',(null as any));
    this._text_70 = this.renderer.createText(this._el_57,'\n      ',(null as any));
    this._text_71 = this.renderer.createText(this._el_46,'\n    ',(null as any));
    this._text_72 = this.renderer.createText(this._el_38,'\n    ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_38,'div',new import3.InlineArray2(2,'class','col-md-2'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'\n      ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_73,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'Add Session',(null as any));
    this._text_77 = this.renderer.createText(this._el_73,'\n    ',(null as any));
    this._text_78 = this.renderer.createText(this._el_38,'\n  ',(null as any));
    this._text_79 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._anchor_80 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_80 = new import10.ViewContainer(80,0,this,this._anchor_80);
    this._TemplateRef_80_5 = new import22.TemplateRef_(this,80,this._anchor_80);
    this._NgIf_80_6 = new import18.Wrapper_NgIf(this._vc_80.vcRef,this._TemplateRef_80_5);
    this._text_81 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_82 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_82 = new import10.ViewContainer(82,0,this,this._anchor_82);
    this._TemplateRef_82_5 = new import22.TemplateRef_(this,82,this._anchor_82);
    this._NgIf_82_6 = new import18.Wrapper_NgIf(this._vc_82.vcRef,this._TemplateRef_82_5);
    this._text_83 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._pipe_uppercase_0 = new import19.UpperCasePipe();
    this._pipe_uppercase_0_0 = import3.pureProxy1(this._pipe_uppercase_0.transform.bind(this._pipe_uppercase_0));
    this._pipe_date_1 = new import20.DatePipe(this.parentView.injectorGet(import23.LOCALE_ID,this.parentIndex));
    this._pipe_date_1_0 = import3.pureProxy2(this._pipe_date_1.transform.bind(this._pipe_date_1));
    this._pipe_currency_2 = new import21.CurrencyPipe(this.parentView.injectorGet(import23.LOCALE_ID,this.parentIndex));
    this._pipe_currency_2_0 = import3.pureProxy3(this._pipe_currency_2.transform.bind(this._pipe_currency_2));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_50,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_50));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_53,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_53));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_59,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_59));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_62,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_62));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_65,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_65));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_68,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_68));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_75,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_75));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._anchor_80,
      this._text_81,
      this._anchor_82,
      this._text_83
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import24.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6.context; }
    if (((token === import22.TemplateRef) && (80 === requestNodeIndex))) { return this._TemplateRef_80_5; }
    if (((token === import24.NgIf) && (80 === requestNodeIndex))) { return this._NgIf_80_6.context; }
    if (((token === import22.TemplateRef) && (82 === requestNodeIndex))) { return this._TemplateRef_82_5; }
    if (((token === import24.NgIf) && (82 === requestNodeIndex))) { return this._NgIf_82_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import11.ValueUnwrapper();
    const currVal_33_0_0:any = (this.context.addMode || ((this.context.event == null)? (null as any): this.context.event.location));
    this._NgIf_33_6.check_ngIf(currVal_33_0_0,throwOnChange,false);
    this._NgIf_33_6.ngDoCheck(this,this._anchor_33,throwOnChange);
    const currVal_80_0_0:boolean = !this.context.addMode;
    this._NgIf_80_6.check_ngIf(currVal_80_0_0,throwOnChange,false);
    this._NgIf_80_6.ngDoCheck(this,this._anchor_80,throwOnChange);
    const currVal_82_0_0:any = this.context.addMode;
    this._NgIf_82_6.check_ngIf(currVal_82_0_0,throwOnChange,false);
    this._NgIf_82_6.ngDoCheck(this,this._anchor_82,throwOnChange);
    this._vc_33.detectChangesInNestedViews(throwOnChange);
    this._vc_80.detectChangesInNestedViews(throwOnChange);
    this._vc_82.detectChangesInNestedViews(throwOnChange);
    const currVal_93:any = ((this.context.event == null)? (null as any): this.context.event.imageUrl);
    if (import3.checkBinding(throwOnChange,this._expr_93,currVal_93)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import25.SecurityContext.URL,currVal_93));
      this._expr_93 = currVal_93;
    }
    const currVal_94:any = ((this.context.event == null)? (null as any): this.context.event.name);
    if (import3.checkBinding(throwOnChange,this._expr_94,currVal_94)) {
      this.renderer.setElementProperty(this._el_2,'alt',currVal_94);
      this._expr_94 = currVal_94;
    }
    valUnwrapper.reset();
    const currVal_95:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_uppercase_0_0,this._pipe_uppercase_0.transform)(((this.context.event == null)? (null as any): this.context.event.name))),' ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_95,currVal_95))) {
      this.renderer.setText(this._text_9,currVal_95);
      this._expr_95 = currVal_95;
    }
    valUnwrapper.reset();
    const currVal_98:any = import3.inlineInterpolate(1,' ',valUnwrapper.unwrap(import3.castByValue(this._pipe_date_1_0,this._pipe_date_1.transform)(((this.context.event == null)? (null as any): this.context.event.date),'shortDate')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_98,currVal_98))) {
      this.renderer.setText(this._text_20,currVal_98);
      this._expr_98 = currVal_98;
    }
    const currVal_101:any = import3.inlineInterpolate(1,' ',((this.context.event == null)? (null as any): this.context.event.time),'');
    if (import3.checkBinding(throwOnChange,this._expr_101,currVal_101)) {
      this.renderer.setText(this._text_25,currVal_101);
      this._expr_101 = currVal_101;
    }
    valUnwrapper.reset();
    const currVal_102:any = import3.inlineInterpolate(1,' ',valUnwrapper.unwrap(import3.castByValue(this._pipe_currency_2_0,this._pipe_currency_2.transform)(((this.context.event == null)? (null as any): this.context.event.price),'USD',true)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_102,currVal_102))) {
      this.renderer.setText(this._text_30,currVal_102);
      this._expr_102 = currVal_102;
    }
    const currVal_105:any = (this.context.sortBy === 'name');
    if (import3.checkBinding(throwOnChange,this._expr_105,currVal_105)) {
      this.renderer.setElementClass(this._el_50,'active',currVal_105);
      this._expr_105 = currVal_105;
    }
    const currVal_106:any = (this.context.sortBy === 'votes');
    if (import3.checkBinding(throwOnChange,this._expr_106,currVal_106)) {
      this.renderer.setElementClass(this._el_53,'active',currVal_106);
      this._expr_106 = currVal_106;
    }
    const currVal_107:any = (this.context.filterBy === 'all');
    if (import3.checkBinding(throwOnChange,this._expr_107,currVal_107)) {
      this.renderer.setElementClass(this._el_59,'active',currVal_107);
      this._expr_107 = currVal_107;
    }
    const currVal_108:any = (this.context.filterBy === 'beginner');
    if (import3.checkBinding(throwOnChange,this._expr_108,currVal_108)) {
      this.renderer.setElementClass(this._el_62,'active',currVal_108);
      this._expr_108 = currVal_108;
    }
    const currVal_109:any = (this.context.filterBy === 'intermediate');
    if (import3.checkBinding(throwOnChange,this._expr_109,currVal_109)) {
      this.renderer.setElementClass(this._el_65,'active',currVal_109);
      this._expr_109 = currVal_109;
    }
    const currVal_110:any = (this.context.filterBy === 'advanced');
    if (import3.checkBinding(throwOnChange,this._expr_110,currVal_110)) {
      this.renderer.setElementClass(this._el_68,'active',currVal_110);
      this._expr_110 = currVal_110;
    }
  }
  destroyInternal():void {
    this._vc_33.destroyNestedViews();
    this._vc_80.destroyNestedViews();
    this._vc_82.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 33)) { return new View_EventDetailsComponent1(this.viewUtils,this,33,this._anchor_33,this._vc_33); }
    if ((nodeIndex == 80)) { return new View_EventDetailsComponent2(this.viewUtils,this,80,this._anchor_80,this._vc_80); }
    if ((nodeIndex == 82)) { return new View_EventDetailsComponent3(this.viewUtils,this,82,this._anchor_82,this._vc_82); }
    return (null as any);
  }
  handleEvent_50(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.sortBy = 'name')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_53(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.sortBy = 'votes')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_59(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.filterBy = 'all')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_62(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.filterBy = 'beginner')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_65(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.filterBy = 'intermediate')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_68(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.filterBy = 'advanced')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_75(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addSession()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}