/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['.votingWidgetContainer[_ngcontent-%COMP%] {\n  padding-left:24px;\n}\n\n.votingWidget[_ngcontent-%COMP%] {\n  height: 64px;\n  padding-top: 7px;\n  border-radius: 21px;\n}\n\n.votingButton[_ngcontent-%COMP%] {\n  margin-left: -7px;\n  margin-top: 1px;\n  cursor:pointer;\n}\n\n.votingButton[_ngcontent-%COMP%]   i[_ngcontent-%COMP%] {\n  color: white;\n}\n\n.badge-inverse[_ngcontent-%COMP%] {\n  background-color: #fff;\n  color: #4e5d6c;\n}\n\n.votingCount[_ngcontent-%COMP%] {\n  margin-left: -11px;\n  margin-top: 1px;\n  font-weight: bold;\n  font-size: 14px;\n}'];
//# sourceMappingURL=upvote.component.css.shim.ngstyle.js.map