/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '../../app/user/user.module';
import * as import10 from '@angular/common/src/localization';
import * as import11 from '@angular/core/src/application_init';
import * as import12 from '@angular/core/src/testability/testability';
import * as import13 from '@angular/core/src/application_ref';
import * as import14 from '@angular/core/src/linker/compiler';
import * as import15 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import16 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import17 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import18 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/animation/animation_queue';
import * as import21 from '@angular/core/src/linker/view_utils';
import * as import22 from '@angular/platform-browser/src/browser/title';
import * as import23 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import24 from '@angular/http/src/backends/browser_xhr';
import * as import25 from '@angular/http/src/base_response_options';
import * as import26 from '@angular/http/src/backends/xhr_backend';
import * as import27 from '@angular/http/src/base_request_options';
import * as import28 from '@angular/forms/src/form_builder';
import * as import29 from '@angular/common/src/location/location';
import * as import30 from '@angular/router/src/url_tree';
import * as import31 from '@angular/router/src/router_outlet_map';
import * as import32 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import33 from '@angular/router/src/router_preloader';
import * as import34 from '../../app/events/shared/event.service';
import * as import35 from '../../app/events/event-resolver.service';
import * as import36 from '../../app/events/events-list-resolver.service';
import * as import37 from '../../app/events/event-details/voter.service';
import * as import38 from '../../app/user/auth.service';
import * as import39 from '@angular/core/src/di/injector';
import * as import40 from './user/profile.component.ngfactory';
import * as import41 from './user/login.component.ngfactory';
import * as import42 from './events/create-event.component.ngfactory';
import * as import43 from './events/events-list.component.ngfactory';
import * as import44 from './events/event-details/event-details.component.ngfactory';
import * as import45 from './events/event-details/create-session.component.ngfactory';
import * as import46 from './errors/404.component.ngfactory';
import * as import47 from './events-app.component.ngfactory';
import * as import48 from '@angular/core/src/i18n/tokens';
import * as import49 from '@angular/core/src/application_tokens';
import * as import50 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import51 from '@angular/platform-browser/src/dom/events/key_events';
import * as import52 from '@angular/core/src/zone/ng_zone';
import * as import53 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import54 from '../../app/user/profile.component';
import * as import55 from '../../app/user/login.component';
import * as import56 from '../../app/events/create-event.component';
import * as import57 from '../../app/events/events-list.component';
import * as import58 from '../../app/events/event-details/event-details.component';
import * as import59 from '../../app/events/event-details/create-session.component';
import * as import60 from '../../app/errors/404.component';
import * as import61 from '@angular/common/src/location/platform_location';
import * as import62 from '@angular/common/src/location/location_strategy';
import * as import63 from '@angular/router/src/url_handling_strategy';
import * as import64 from '@angular/router/src/route_reuse_strategy';
import * as import65 from '@angular/router/src/router';
import * as import66 from '@angular/core/src/console';
import * as import67 from '@angular/core/src/error_handler';
import * as import68 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import69 from '@angular/platform-browser/src/dom/animation_driver';
import * as import70 from '@angular/core/src/render/api';
import * as import71 from '@angular/core/src/security';
import * as import72 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import73 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import74 from '@angular/http/src/interfaces';
import * as import75 from '@angular/http/src/http';
import * as import76 from '@angular/router/src/router_config_loader';
import * as import77 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import78 from '@angular/router/src/router_state';
import * as import79 from '../../app/common/toastr.service';
import * as import80 from '../../app/common/jQuery.service';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _ReactiveFormsModule_6:import6.ReactiveFormsModule;
  _ROUTER_FORROOT_GUARD_7:any;
  _RouterModule_8:import8.RouterModule;
  _UserModule_9:import9.UserModule;
  _AppModule_10:import1.AppModule;
  __LOCALE_ID_11:any;
  __NgLocalization_12:import10.NgLocaleLocalization;
  _ErrorHandler_13:any;
  _RouterInitializer_14:import8.RouterInitializer;
  _APP_INITIALIZER_15:any[];
  _ApplicationInitStatus_16:import11.ApplicationInitStatus;
  _Testability_17:import12.Testability;
  _ApplicationRef__18:import13.ApplicationRef_;
  __ApplicationRef_19:any;
  __Compiler_20:import14.Compiler;
  __APP_ID_21:any;
  __DOCUMENT_22:any;
  __HAMMER_GESTURE_CONFIG_23:import15.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_24:any[];
  __EventManager_25:import16.EventManager;
  _DomSharedStylesHost_26:import17.DomSharedStylesHost;
  __AnimationDriver_27:any;
  __DomRootRenderer_28:import18.DomRootRenderer_;
  __NgProbeToken_29:any[];
  __RootRenderer_30:any;
  __DomSanitizer_31:import19.DomSanitizerImpl;
  __Sanitizer_32:any;
  __AnimationQueue_33:import20.AnimationQueue;
  __ViewUtils_34:import21.ViewUtils;
  __IterableDiffers_35:any;
  __KeyValueDiffers_36:any;
  __SharedStylesHost_37:any;
  __Title_38:import22.Title;
  __RadioControlRegistry_39:import23.RadioControlRegistry;
  __BrowserXhr_40:import24.BrowserXhr;
  __ResponseOptions_41:import25.BaseResponseOptions;
  __XSRFStrategy_42:any;
  __XHRBackend_43:import26.XHRBackend;
  __RequestOptions_44:import27.BaseRequestOptions;
  __Http_45:any;
  __FormBuilder_46:import28.FormBuilder;
  __ROUTES_47:any[];
  __ROUTER_CONFIGURATION_48:any;
  __LocationStrategy_49:any;
  __Location_50:import29.Location;
  __UrlSerializer_51:import30.DefaultUrlSerializer;
  __RouterOutletMap_52:import31.RouterOutletMap;
  __NgModuleFactoryLoader_53:import32.SystemJsNgModuleLoader;
  __Router_54:any;
  __ActivatedRoute_55:any;
  _NoPreloading_56:import33.NoPreloading;
  _PreloadingStrategy_57:any;
  _RouterPreloader_58:import33.RouterPreloader;
  __PreloadAllModules_59:import33.PreloadAllModules;
  __ROUTER_INITIALIZER_60:any;
  __APP_BOOTSTRAP_LISTENER_61:any[];
  __EventService_62:import34.EventService;
  __TOASTR_TOKEN_63:any;
  __JQ_TOKEN_64:any;
  __EventResolver_65:import35.EventResolver;
  __EventListResolver_66:import36.EventListResolver;
  __VoterService_67:import37.VoterService;
  __AuthService_68:import38.AuthService;
  __canDeactivateCreateEvent_69:any;
  constructor(parent:import39.Injector) {
    super(parent,[
      import40.ProfileComponentNgFactory,
      import41.LoginComponentNgFactory,
      import42.CreateEventComponentNgFactory,
      import43.EventsListComponentNgFactory,
      import44.EventDetailsComponentNgFactory,
      import45.CreateSessionComponentNgFactory,
      import46.Error404ComponentNgFactory,
      import47.EventsAppComponentNgFactory
    ]
    ,[import47.EventsAppComponentNgFactory]);
  }
  get _LOCALE_ID_11():any {
    if ((this.__LOCALE_ID_11 == null)) { (this.__LOCALE_ID_11 = import3._localeFactory(this.parent.get(import48.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_11;
  }
  get _NgLocalization_12():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_12 == null)) { (this.__NgLocalization_12 = new import10.NgLocaleLocalization(this._LOCALE_ID_11)); }
    return this.__NgLocalization_12;
  }
  get _ApplicationRef_19():any {
    if ((this.__ApplicationRef_19 == null)) { (this.__ApplicationRef_19 = this._ApplicationRef__18); }
    return this.__ApplicationRef_19;
  }
  get _Compiler_20():import14.Compiler {
    if ((this.__Compiler_20 == null)) { (this.__Compiler_20 = new import14.Compiler()); }
    return this.__Compiler_20;
  }
  get _APP_ID_21():any {
    if ((this.__APP_ID_21 == null)) { (this.__APP_ID_21 = import49._appIdRandomProviderFactory()); }
    return this.__APP_ID_21;
  }
  get _DOCUMENT_22():any {
    if ((this.__DOCUMENT_22 == null)) { (this.__DOCUMENT_22 = import4._document()); }
    return this.__DOCUMENT_22;
  }
  get _HAMMER_GESTURE_CONFIG_23():import15.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_23 == null)) { (this.__HAMMER_GESTURE_CONFIG_23 = new import15.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_23;
  }
  get _EVENT_MANAGER_PLUGINS_24():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_24 == null)) { (this.__EVENT_MANAGER_PLUGINS_24 = [
      new import50.DomEventsPlugin(),
      new import51.KeyEventsPlugin(),
      new import15.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_23)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_24;
  }
  get _EventManager_25():import16.EventManager {
    if ((this.__EventManager_25 == null)) { (this.__EventManager_25 = new import16.EventManager(this._EVENT_MANAGER_PLUGINS_24,this.parent.get(import52.NgZone))); }
    return this.__EventManager_25;
  }
  get _AnimationDriver_27():any {
    if ((this.__AnimationDriver_27 == null)) { (this.__AnimationDriver_27 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_27;
  }
  get _DomRootRenderer_28():import18.DomRootRenderer_ {
    if ((this.__DomRootRenderer_28 == null)) { (this.__DomRootRenderer_28 = new import18.DomRootRenderer_(this._DOCUMENT_22,this._EventManager_25,this._DomSharedStylesHost_26,this._AnimationDriver_27,this._APP_ID_21)); }
    return this.__DomRootRenderer_28;
  }
  get _NgProbeToken_29():any[] {
    if ((this.__NgProbeToken_29 == null)) { (this.__NgProbeToken_29 = [import8.routerNgProbeToken()]); }
    return this.__NgProbeToken_29;
  }
  get _RootRenderer_30():any {
    if ((this.__RootRenderer_30 == null)) { (this.__RootRenderer_30 = import53._createConditionalRootRenderer(this._DomRootRenderer_28,this.parent.get(import53.NgProbeToken,(null as any)),this._NgProbeToken_29)); }
    return this.__RootRenderer_30;
  }
  get _DomSanitizer_31():import19.DomSanitizerImpl {
    if ((this.__DomSanitizer_31 == null)) { (this.__DomSanitizer_31 = new import19.DomSanitizerImpl()); }
    return this.__DomSanitizer_31;
  }
  get _Sanitizer_32():any {
    if ((this.__Sanitizer_32 == null)) { (this.__Sanitizer_32 = this._DomSanitizer_31); }
    return this.__Sanitizer_32;
  }
  get _AnimationQueue_33():import20.AnimationQueue {
    if ((this.__AnimationQueue_33 == null)) { (this.__AnimationQueue_33 = new import20.AnimationQueue(this.parent.get(import52.NgZone))); }
    return this.__AnimationQueue_33;
  }
  get _ViewUtils_34():import21.ViewUtils {
    if ((this.__ViewUtils_34 == null)) { (this.__ViewUtils_34 = new import21.ViewUtils(this._RootRenderer_30,this._Sanitizer_32,this._AnimationQueue_33)); }
    return this.__ViewUtils_34;
  }
  get _IterableDiffers_35():any {
    if ((this.__IterableDiffers_35 == null)) { (this.__IterableDiffers_35 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_35;
  }
  get _KeyValueDiffers_36():any {
    if ((this.__KeyValueDiffers_36 == null)) { (this.__KeyValueDiffers_36 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_36;
  }
  get _SharedStylesHost_37():any {
    if ((this.__SharedStylesHost_37 == null)) { (this.__SharedStylesHost_37 = this._DomSharedStylesHost_26); }
    return this.__SharedStylesHost_37;
  }
  get _Title_38():import22.Title {
    if ((this.__Title_38 == null)) { (this.__Title_38 = new import22.Title()); }
    return this.__Title_38;
  }
  get _RadioControlRegistry_39():import23.RadioControlRegistry {
    if ((this.__RadioControlRegistry_39 == null)) { (this.__RadioControlRegistry_39 = new import23.RadioControlRegistry()); }
    return this.__RadioControlRegistry_39;
  }
  get _BrowserXhr_40():import24.BrowserXhr {
    if ((this.__BrowserXhr_40 == null)) { (this.__BrowserXhr_40 = new import24.BrowserXhr()); }
    return this.__BrowserXhr_40;
  }
  get _ResponseOptions_41():import25.BaseResponseOptions {
    if ((this.__ResponseOptions_41 == null)) { (this.__ResponseOptions_41 = new import25.BaseResponseOptions()); }
    return this.__ResponseOptions_41;
  }
  get _XSRFStrategy_42():any {
    if ((this.__XSRFStrategy_42 == null)) { (this.__XSRFStrategy_42 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_42;
  }
  get _XHRBackend_43():import26.XHRBackend {
    if ((this.__XHRBackend_43 == null)) { (this.__XHRBackend_43 = new import26.XHRBackend(this._BrowserXhr_40,this._ResponseOptions_41,this._XSRFStrategy_42)); }
    return this.__XHRBackend_43;
  }
  get _RequestOptions_44():import27.BaseRequestOptions {
    if ((this.__RequestOptions_44 == null)) { (this.__RequestOptions_44 = new import27.BaseRequestOptions()); }
    return this.__RequestOptions_44;
  }
  get _Http_45():any {
    if ((this.__Http_45 == null)) { (this.__Http_45 = import7.httpFactory(this._XHRBackend_43,this._RequestOptions_44)); }
    return this.__Http_45;
  }
  get _FormBuilder_46():import28.FormBuilder {
    if ((this.__FormBuilder_46 == null)) { (this.__FormBuilder_46 = new import28.FormBuilder()); }
    return this.__FormBuilder_46;
  }
  get _ROUTES_47():any[] {
    if ((this.__ROUTES_47 == null)) { (this.__ROUTES_47 = [
      [
        {
          path: 'profile',
          component: import54.ProfileComponent
        }
        ,
        {
          path: 'login',
          component: import55.LoginComponent
        }

      ]
      ,
      [
        {
          path: 'events/new',
          component: import56.CreateEventComponent,
          canDeactivate: ['canDeactivateCreateEvent']
        }
        ,
        {
          path: 'events',
          component: import57.EventsListComponent,
          resolve: {events: import36.EventListResolver}
        }
        ,
        {
          path: 'events/:id',
          component: import58.EventDetailsComponent,
          resolve: {event: import35.EventResolver}
        }
        ,
        {
          path: 'events/session/new',
          component: import59.CreateSessionComponent
        }
        ,
        {
          path: '404',
          component: import60.Error404Component
        }
        ,
        {
          path: '',
          redirectTo: '/events',
          pathMatch: 'full'
        }
        ,
        {
          path: 'user',
          children: [
            {
              path: 'profile',
              component: import54.ProfileComponent
            }
            ,
            {
              path: 'login',
              component: import55.LoginComponent
            }

          ]

        }

      ]

    ]
    ); }
    return this.__ROUTES_47;
  }
  get _ROUTER_CONFIGURATION_48():any {
    if ((this.__ROUTER_CONFIGURATION_48 == null)) { (this.__ROUTER_CONFIGURATION_48 = {}); }
    return this.__ROUTER_CONFIGURATION_48;
  }
  get _LocationStrategy_49():any {
    if ((this.__LocationStrategy_49 == null)) { (this.__LocationStrategy_49 = import8.provideLocationStrategy(this.parent.get(import61.PlatformLocation),this.parent.get(import62.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_48)); }
    return this.__LocationStrategy_49;
  }
  get _Location_50():import29.Location {
    if ((this.__Location_50 == null)) { (this.__Location_50 = new import29.Location(this._LocationStrategy_49)); }
    return this.__Location_50;
  }
  get _UrlSerializer_51():import30.DefaultUrlSerializer {
    if ((this.__UrlSerializer_51 == null)) { (this.__UrlSerializer_51 = new import30.DefaultUrlSerializer()); }
    return this.__UrlSerializer_51;
  }
  get _RouterOutletMap_52():import31.RouterOutletMap {
    if ((this.__RouterOutletMap_52 == null)) { (this.__RouterOutletMap_52 = new import31.RouterOutletMap()); }
    return this.__RouterOutletMap_52;
  }
  get _NgModuleFactoryLoader_53():import32.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_53 == null)) { (this.__NgModuleFactoryLoader_53 = new import32.SystemJsNgModuleLoader(this._Compiler_20,this.parent.get(import32.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_53;
  }
  get _Router_54():any {
    if ((this.__Router_54 == null)) { (this.__Router_54 = import8.setupRouter(this._ApplicationRef_19,this._UrlSerializer_51,this._RouterOutletMap_52,this._Location_50,this,this._NgModuleFactoryLoader_53,this._Compiler_20,this._ROUTES_47,this._ROUTER_CONFIGURATION_48,this.parent.get(import63.UrlHandlingStrategy,(null as any)),this.parent.get(import64.RouteReuseStrategy,(null as any)))); }
    return this.__Router_54;
  }
  get _ActivatedRoute_55():any {
    if ((this.__ActivatedRoute_55 == null)) { (this.__ActivatedRoute_55 = import8.rootRoute(this._Router_54)); }
    return this.__ActivatedRoute_55;
  }
  get _PreloadAllModules_59():import33.PreloadAllModules {
    if ((this.__PreloadAllModules_59 == null)) { (this.__PreloadAllModules_59 = new import33.PreloadAllModules()); }
    return this.__PreloadAllModules_59;
  }
  get _ROUTER_INITIALIZER_60():any {
    if ((this.__ROUTER_INITIALIZER_60 == null)) { (this.__ROUTER_INITIALIZER_60 = import8.getBootstrapListener(this._RouterInitializer_14)); }
    return this.__ROUTER_INITIALIZER_60;
  }
  get _APP_BOOTSTRAP_LISTENER_61():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_61 == null)) { (this.__APP_BOOTSTRAP_LISTENER_61 = [this._ROUTER_INITIALIZER_60]); }
    return this.__APP_BOOTSTRAP_LISTENER_61;
  }
  get _EventService_62():import34.EventService {
    if ((this.__EventService_62 == null)) { (this.__EventService_62 = new import34.EventService(this._Http_45)); }
    return this.__EventService_62;
  }
  get _TOASTR_TOKEN_63():any {
    if ((this.__TOASTR_TOKEN_63 == null)) { (this.__TOASTR_TOKEN_63 = (undefined as any)); }
    return this.__TOASTR_TOKEN_63;
  }
  get _JQ_TOKEN_64():any {
    if ((this.__JQ_TOKEN_64 == null)) { (this.__JQ_TOKEN_64 = (undefined as any)); }
    return this.__JQ_TOKEN_64;
  }
  get _EventResolver_65():import35.EventResolver {
    if ((this.__EventResolver_65 == null)) { (this.__EventResolver_65 = new import35.EventResolver(this._EventService_62)); }
    return this.__EventResolver_65;
  }
  get _EventListResolver_66():import36.EventListResolver {
    if ((this.__EventListResolver_66 == null)) { (this.__EventListResolver_66 = new import36.EventListResolver(this._EventService_62)); }
    return this.__EventListResolver_66;
  }
  get _VoterService_67():import37.VoterService {
    if ((this.__VoterService_67 == null)) { (this.__VoterService_67 = new import37.VoterService(this._Http_45)); }
    return this.__VoterService_67;
  }
  get _AuthService_68():import38.AuthService {
    if ((this.__AuthService_68 == null)) { (this.__AuthService_68 = new import38.AuthService(this._Http_45)); }
    return this.__AuthService_68;
  }
  get _canDeactivateCreateEvent_69():any {
    if ((this.__canDeactivateCreateEvent_69 == null)) { (this.__canDeactivateCreateEvent_69 = import1.checkDirtyState); }
    return this.__canDeactivateCreateEvent_69;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._ReactiveFormsModule_6 = new import6.ReactiveFormsModule();
    this._ROUTER_FORROOT_GUARD_7 = import8.provideForRootGuard(this.parent.get(import65.Router,(null as any)));
    this._RouterModule_8 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_7);
    this._UserModule_9 = new import9.UserModule();
    this._AppModule_10 = new import1.AppModule();
    this._ErrorHandler_13 = import4.errorHandler();
    this._RouterInitializer_14 = new import8.RouterInitializer(this);
    this._APP_INITIALIZER_15 = [import8.getAppInitializer(this._RouterInitializer_14)];
    this._ApplicationInitStatus_16 = new import11.ApplicationInitStatus(this._APP_INITIALIZER_15);
    this._Testability_17 = new import12.Testability(this.parent.get(import52.NgZone));
    this._ApplicationRef__18 = new import13.ApplicationRef_(this.parent.get(import52.NgZone),this.parent.get(import66.Console),this,this._ErrorHandler_13,this,this._ApplicationInitStatus_16,this.parent.get(import12.TestabilityRegistry,(null as any)),this._Testability_17);
    this._DomSharedStylesHost_26 = new import17.DomSharedStylesHost(this._DOCUMENT_22);
    this._NoPreloading_56 = new import33.NoPreloading();
    this._PreloadingStrategy_57 = this._NoPreloading_56;
    this._RouterPreloader_58 = new import33.RouterPreloader(this._Router_54,this._NgModuleFactoryLoader_53,this._Compiler_20,this,this._PreloadingStrategy_57);
    return this._AppModule_10;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_6; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_7; }
    if ((token === import8.RouterModule)) { return this._RouterModule_8; }
    if ((token === import9.UserModule)) { return this._UserModule_9; }
    if ((token === import1.AppModule)) { return this._AppModule_10; }
    if ((token === import48.LOCALE_ID)) { return this._LOCALE_ID_11; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_12; }
    if ((token === import67.ErrorHandler)) { return this._ErrorHandler_13; }
    if ((token === import8.RouterInitializer)) { return this._RouterInitializer_14; }
    if ((token === import11.APP_INITIALIZER)) { return this._APP_INITIALIZER_15; }
    if ((token === import11.ApplicationInitStatus)) { return this._ApplicationInitStatus_16; }
    if ((token === import12.Testability)) { return this._Testability_17; }
    if ((token === import13.ApplicationRef_)) { return this._ApplicationRef__18; }
    if ((token === import13.ApplicationRef)) { return this._ApplicationRef_19; }
    if ((token === import14.Compiler)) { return this._Compiler_20; }
    if ((token === import49.APP_ID)) { return this._APP_ID_21; }
    if ((token === import68.DOCUMENT)) { return this._DOCUMENT_22; }
    if ((token === import15.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_23; }
    if ((token === import16.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_24; }
    if ((token === import16.EventManager)) { return this._EventManager_25; }
    if ((token === import17.DomSharedStylesHost)) { return this._DomSharedStylesHost_26; }
    if ((token === import69.AnimationDriver)) { return this._AnimationDriver_27; }
    if ((token === import18.DomRootRenderer)) { return this._DomRootRenderer_28; }
    if ((token === import13.NgProbeToken)) { return this._NgProbeToken_29; }
    if ((token === import70.RootRenderer)) { return this._RootRenderer_30; }
    if ((token === import19.DomSanitizer)) { return this._DomSanitizer_31; }
    if ((token === import71.Sanitizer)) { return this._Sanitizer_32; }
    if ((token === import20.AnimationQueue)) { return this._AnimationQueue_33; }
    if ((token === import21.ViewUtils)) { return this._ViewUtils_34; }
    if ((token === import72.IterableDiffers)) { return this._IterableDiffers_35; }
    if ((token === import73.KeyValueDiffers)) { return this._KeyValueDiffers_36; }
    if ((token === import17.SharedStylesHost)) { return this._SharedStylesHost_37; }
    if ((token === import22.Title)) { return this._Title_38; }
    if ((token === import23.RadioControlRegistry)) { return this._RadioControlRegistry_39; }
    if ((token === import24.BrowserXhr)) { return this._BrowserXhr_40; }
    if ((token === import25.ResponseOptions)) { return this._ResponseOptions_41; }
    if ((token === import74.XSRFStrategy)) { return this._XSRFStrategy_42; }
    if ((token === import26.XHRBackend)) { return this._XHRBackend_43; }
    if ((token === import27.RequestOptions)) { return this._RequestOptions_44; }
    if ((token === import75.Http)) { return this._Http_45; }
    if ((token === import28.FormBuilder)) { return this._FormBuilder_46; }
    if ((token === import76.ROUTES)) { return this._ROUTES_47; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_48; }
    if ((token === import62.LocationStrategy)) { return this._LocationStrategy_49; }
    if ((token === import29.Location)) { return this._Location_50; }
    if ((token === import30.UrlSerializer)) { return this._UrlSerializer_51; }
    if ((token === import31.RouterOutletMap)) { return this._RouterOutletMap_52; }
    if ((token === import77.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_53; }
    if ((token === import65.Router)) { return this._Router_54; }
    if ((token === import78.ActivatedRoute)) { return this._ActivatedRoute_55; }
    if ((token === import33.NoPreloading)) { return this._NoPreloading_56; }
    if ((token === import33.PreloadingStrategy)) { return this._PreloadingStrategy_57; }
    if ((token === import33.RouterPreloader)) { return this._RouterPreloader_58; }
    if ((token === import33.PreloadAllModules)) { return this._PreloadAllModules_59; }
    if ((token === import8.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_60; }
    if ((token === import49.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_61; }
    if ((token === import34.EventService)) { return this._EventService_62; }
    if ((token === import79.TOASTR_TOKEN)) { return this._TOASTR_TOKEN_63; }
    if ((token === import80.JQ_TOKEN)) { return this._JQ_TOKEN_64; }
    if ((token === import35.EventResolver)) { return this._EventResolver_65; }
    if ((token === import36.EventListResolver)) { return this._EventListResolver_66; }
    if ((token === import37.VoterService)) { return this._VoterService_67; }
    if ((token === import38.AuthService)) { return this._AuthService_68; }
    if ((token === 'canDeactivateCreateEvent')) { return this._canDeactivateCreateEvent_69; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__18.ngOnDestroy();
    this._DomSharedStylesHost_26.ngOnDestroy();
    this._RouterPreloader_58.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);